name: Deploy Todo App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Create S3 Bucket
      run: |
        aws s3api create-bucket \
          --bucket todo-app-tf-state-oktay \
          --region eu-central-1 \
          --create-bucket-configuration LocationConstraint=eu-central-1

    - name: Create DynamoDB Table
      run: |
        aws dynamodb create-table \
          --table-name terraform-lock \
          --attribute-definitions AttributeName=LockID,AttributeType=S \
          --key-schema AttributeName=LockID,KeyType=HASH \
          --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
          --region eu-central-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform-workspace: main

    - name: Terraform Init & Apply
      id: terraform
      run: |
        cd infrastructure/terraform
        terraform init -reconfigure -input=false
        terraform apply -auto-approve -var="iam_user_name=${{ secrets.IAM_USER_NAME }}" -refresh=false
        
        # Çıktıları dosyaya yaz
        terraform output -raw ec2_public_ip | tr -d '\r' > ec2_ip.txt
        terraform output -raw private_key > private_key.pem
        
        # Environment variables tanımla
        echo "EC2_IP=$(cat ec2_ip.txt)" >> $GITHUB_ENV
        echo "PRIVATE_KEY_FILE=${GITHUB_WORKSPACE}/infrastructure/terraform/private_key.pem" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Configure Frontend
      run: |
        echo "REACT_APP_API_URL=http://$(terraform -chdir=infrastructure/terraform output -raw ec2_public_ip):3001" > frontend/.env

    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Deploy Frontend
      run: |
        aws s3 sync frontend/build/ s3://todo-app-frontend-bucket-oktay --delete

    - name: Deploy Backend
      run: |
        EC2_IP=${{ env.EC2_IP }}
        # Artifact'tan private key'i al
        chmod 600 ${{ env.PRIVATE_KEY_FILE }}
        
        scp -i ${{ env.PRIVATE_KEY_FILE }} -o StrictHostKeyChecking=no -r backend/* ec2-user@$EC2_IP:/home/ec2-user/app/
        ssh -i ${{ env.PRIVATE_KEY_FILE }} ec2-user@$EC2_IP "cd /home/ec2-user/app && npm ci && pm2 restart all" 