name: Deploy Todo App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    - name: Configure Frontend
      run: |
        echo "REACT_APP_API_URL=http://${{ secrets.EC2_IP }}:3001" > frontend/.env

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Deploy Frontend
      run: |
        aws s3 sync frontend/build/ s3://${{ secrets.S3_BUCKET }} --delete

    - name: Deploy Backend
      run: |
        # SSH key'i oluştur
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        
        # Backend dosyalarını kopyala
        scp -i private_key.pem -o StrictHostKeyChecking=no -r backend/* ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/app/
        
        # Backend'i yeniden başlat
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "
          cd /home/ec2-user/app && 
          npm ci && 
          pm2 delete all || true && 
          pm2 start src/server.js --name todo-backend
        "
        
        # Temizlik
        rm -f private_key.pem 